POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "name":"njenien",
  "email": "jeni.riskaa@gmail.com",
  "password": "name",
  "password_confirmation": "name"
}

###
POST http://localhost:3000/api/v1/authenticate/login
Content-Type: application/json

{
  "email": "nameke1@gmail.com",
  "password": "name"
}
###
GET http://localhost:3000