POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "name":"juni",
  "email": "soseho1817@bustayes.com",
  "password": "pp",
  "password_confirmation": "pp"
}

###
  
POST http://localhost:3000/api/v1/auth/activate-account
Content-Type: application/json

{
    "email": "leseme4317@dpsols.com",
    "otp":"hQBtaE"
}

###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "leseme4317@dpsols.com",
  "password": "pp",
}
