POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "name":"njenien",
  "email": "xenes38278@bikedid.com",
  "password": "name",
  "password_confirmation": "name"
}

###
 
POST http://localhost:3000/api/v1/auth/forgot-password
Content-Type: application/json

{
    "email": "xenes38278@bikedid.com"
}

###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "xenes38278@bikedid.com",
  "password": "sip"
}
###
GET http://localhost:3000